public interface logicsInterface {
    public boolean sleepIn(boolean weekday, boolean vacation);
    public boolean monkeyTrouble(boolean aSmile, boolean bSmile);
    public int sumDouble(int a, int b);
    public int diff21(int n);
    public boolean parrotTrouble(boolean talking, int hour);
    public boolean makes10(int a, int b);
    public boolean nearHundred(int n);
    public boolean posNeg(int a, int b, boolean negative);
    public String notString(String str);
    public String missingChar(String str, int n);
    public String frontBack(String str) ;
    public String front3(String str);
    public String backAround(String str);
    public boolean or35(int n);
    public String front22(String str) ;
    public boolean startHi(String str);
    public boolean icyHot(int temp1, int temp2);
    public int close10(int a, int b);
    public boolean in3050(int a, int b);
    public int max1020(int a, int b);
    public boolean stringE(String str) ;
    public int intMax(int a, int b, int c);
    public String startOz(String str);
    public boolean lastDigit(int a, int b);
     public String endUp(String str);
     public String everyNth(String str, int n);
     public String stringTimes(String str, int n);
     public String frontTimes(String str, int n);
     int countXX(String str);
     public boolean doubleX(String str);
     public String stringBits(String str);
     public String stringSplosion(String str);
     public int last2(String str);
      public int arrayCount9(int[] nums) ;
      public boolean arrayFront9(int[] nums);
    public int stringMatch(String a, String b) ;
    public String stringX(String str);
    public String altPairs(String str) ;
    public String stringYak(String str);
    public int array667(int[] nums);
    public boolean noTriples(int[] nums);
    public boolean has271(int[] nums);
    public boolean array123(int[] nums);
    public String without2(String str);
    public String deFront(String str);
    public String startWord(String str, String word);
    public String withoutX(String str);
    public String withoutX2(String str);
    public boolean catDog(String str);  
    public boolean xyzThere(String str);
    public boolean bobThere(String str);    
    public boolean endOther(String a, String b);
    public boolean xyBalance(String str);
    public String mixString(String a, String b);
      public String repeatEnd(String str, int n);  
      public String repeatFront(String str, int n) ; 
      public String repeatSeparator(String word, String sep, int count);
      public boolean prefixAgain(String str, int n);
      public boolean xyzMiddle(String str)  ;
      public String getSandwich(String str);
      public boolean sameStarChar(String str);
      public String oneTwo(String str);
      public String zipZap(String str); 
      public String starOut(String str);
      public String plusOut(String str, String word) ;
      public String wordEnds(String str, String word) ;
      public boolean firstLast6(int[] nums);
      public boolean sameFirstLast(int[] nums);
      public int[] makePi();
      public boolean commonEnd(int[] a, int[] b);
      public int sum3(int[] nums);
       public int[] rotateLeft3(int[] nums);
       public int[] reverse3(int[] nums);
       public int[] maxEnd3(int[] nums);
       public int[] middleWay(int[] a, int[] b) ;
       public int[] makeEnds(int[] nums) ;
        public boolean has23(int[] nums);
        public boolean no23(int[] nums);
      public boolean double23(int[] nums);
      public int[] fix23(int[] nums);
      public int start1(int[] a, int[] b) ;
      public int[] biggerTwo(int[] a, int[] b);
      public int[] makeMiddle(int[] nums) ;
      public int[] plusTwo(int[] a, int[] b)  ;
      public int[] swapEnds(int[] nums);
      public int[] midThree(int[] nums);
       public int maxTriple(int[] nums) ;
       public int[] frontPiece(int[] nums);
       public boolean unlucky1(int[] nums);
       public int[] make2(int[] a, int[] b);
       public int[] front11(int[] a, int[] b);
       public int countEvens(int[] nums);
       public int bigDiff(int[] nums);
       public int centeredAverage(int[] nums) ;
       public int sum13(int[] nums) ; 
       public int sum67(int[] nums);  
       public boolean has22(int[] nums);
       public boolean lucky13(int[] nums);
       public boolean sum28(int[] nums);
       public boolean more14(int[] nums);
       public int[] fizzArray(int n);
        public boolean only14(int[] nums);
        public String[] fizzArray2(int n);
        public boolean no14(int[] nums) ;
        public boolean isEverywhere(int[] nums, int val);
        public boolean either24(int[] nums);
        public int matchUp(int[] nums1, int[] nums2);
        public boolean has77(int[] nums);
        public boolean has12(int[] nums);
        public boolean modThree(int[] nums);
        public boolean haveThree(int[] nums);
        public boolean twoTwo(int[] nums);
        public boolean sameEnds(int[] nums, int len);
        public boolean tripleUp(int[] nums);
        public int[] fizzArray3(int start, int end);
        public int[] shiftLeft(int[] nums); 
        public int[] tenRun(int[] nums);
        public int[] pre4(int[] nums);
        public int[] post4(int[] nums);
        public int[] notAlone(int[] nums, int val);
        public int[] zeroFront(int[] nums);
        public int[] withoutTen(int[] nums);
        public int[] zeroMax(int[] nums);
}
